-- ═══════════════════════════════════════════════════════════════════════════
-- 20250817_fix_empty_jpk_articles.sql
-- JPK (Jinoyat-protsessual kodeksi) da bo'sh/qisqartirilgan qolgan 3 ta modda
-- matnini rasmiy manba (lex.uz) dan to'ldirish.
--
-- Qaysi moddalar: 324 (Shaxslarning arizalari), 327 (Ommaviy axborot vositalari),
--                 382 (Prokurorning vakolatlari)
-- Manba: https://lex.uz/docs/-111460 (O'zbekiston Respublikasining Jinoyat-protsessual kodeksi)
-- ═══════════════════════════════════════════════════════════════════════════

-- 324-modda. Shaxslarning arizalari
UPDATE public.articles
SET title = 'Shaxslarning arizalari',
    content = $article324$Shaxslarning jinoyat toʻgʻrisidagi arizalari yozma yoki ogʻzaki boʻlishi mumkin. Yozma ariza arz qiluvchi shaxs tomonidan imzolangan boʻlishi lozim. Ogʻzaki ariza bayonnomada qayd etiladi. Bayonnomada arz qiluvchi, uning yashash va ishlash joyi, shuningdek shaxsiy hujjatlari toʻgʻrisidagi maʼlumotlar aks ettirilishi lozim. Basharti arz qiluvchi hujjat koʻrsata olmasa, uning shaxsi toʻgʻrisidagi maʼlumotlarni boshqa yoʻllar bilan tekshirish chorasi koʻrilishi kerak. Arz qiluvchi jinoyat toʻgʻrisida bila turib yolgʻon xabar berganlik uchun jinoiy javobgarlikka tortilishi haqida ogohlantiriladi va bu xususda bayonnomada qayd qilinib, uning imzosi bilan tasdiqlanadi. Soʻngra bayonnomada jinoyat sodir etish holatlari xususidagi maʼlumotlar arz qiluvchi nomidan, iloji boricha soʻzma-soʻz aks ettiriladi. Bayonnomani arz qiluvchi va arizani qabul qilgan mansabdor shaxs imzolaydilar. Jinoyat ishini qoʻzgʻatishga ushbu Kodeksning 113-moddasida nazarda tutilgan aybini boʻyniga olish toʻgʻrisidagi arz sabab boʻlsa, bila turib yolgʻon xabar berganlik uchun jinoiy javobgarlikka tortilishi toʻgʻrisida ogohlantirilmasligini mustasno etganda, unga shaxslarning arizalarini qabul qilish va rasmiylashtirish toʻgʻrisidagi ushbu moddada nazarda tutilgan barcha qoidalar taalluqlidir.$article324$
WHERE code_id = 'criminal_procedure_code' AND article_number = '324';

-- 327-modda. Ommaviy axborot vositalari bergan xabarlar
UPDATE public.articles
SET title = 'Ommaviy axborot vositalari',
    content = $article327$Muayyan jinoyat toʻgʻrisida matbuot, radio va televideniye, hujjatli kinofilmlardagi, shuningdek ommaviy axborot vositalariga yoʻllangan, lekin eʼlon qilinmagan xatlardagi xabarlar jinoyat ishini qoʻzgʻatishga sabab boʻladi. Jinoyat toʻgʻrisidagi xabarni eʼlon qilgan yoki tegishli joylarga yuborgan ommaviy axborot vositalari, shuningdek bu xabar mualliflari surishtiruvchi, tergovchi, prokuror yoki sudning talabiga asosan oʻz ixtiyorlarida boʻlgan hujjatlarni va xabarni tasdiqlovchi boshqa materiallarni taqdim qilishlari shart.$article327$
WHERE code_id = 'criminal_procedure_code' AND article_number = '327';

-- 382-modda. Prokurorning vakolatlari
UPDATE public.articles
SET title = 'Prokurorning vakolatlari',
    content = $article382$Surishtiruv va dastlabki tergov harakatlarini yuritishda qonunlarning ijro etilishi ustidan nazorat prokuror tomonidan amalga oshiriladi. Jinoyat sodir etilgani toʻgʻrisidagi ariza va xabarlarni koʻrish hamda hal qilish, tekshirishni amalga oshirishning ushbu Kodeksda belgilangan tartibi, chiqarilgan qarorlarning qonuniyligi surishtiruv va dastlabki tergov organlarining qonunlarning ijro etilishi ustidan olib boradigan nazoratining sohasidir. Surishtiruv va dastlabki tergov organlari tomonidan qonunlarning ijro etilishi ustidan nazoratni amalga oshirib, prokuror oʻz vakolati doirasida: surishtiruv va dastlabki tergov organlaridan hamda tergovga qadar tekshiruvni yoki tezkor-qidiruv faoliyatini amalga oshiruvchi organlardan ishlarni tekshirish uchun, sodir etilgan jinoyatlarga oid tezkor-qidiruv, surishtiruv, dastlabki tergov ishlarining borishiga doir hujjatlarni, materiallarni va boshqa maʼlumotlarni talab qilib oladi; sodir etilgan yoki tayyorlanayotgan jinoyatlar haqidagi ariza va maʼlumotlarni qabul qilish, roʻyxatdan oʻtkazish va hal etish toʻgʻrisidagi qonun talablari qay darajada ijro etilayotganligini har oy kamida bir marta tekshiradi; surishtiruvchilar va tergovchilarning shuningdek tergovga qadar tekshiruvni amalga oshiruvchi organ mansabdor shaxsining qonunga xilof hamda asossiz qarorlarini bekor qiladi; jinoyatlarni tergov qilish, ehtiyot chorasini tanlash, oʻzgartirish yoki bekor qilish, uy qamogʻi boʻyicha qoʻshimcha taqiq (cheklov) belgilash haqida iltimosnoma qoʻzgʻatish jinoyat tavsifini belgilash, ishda ayblanuvchi tariqasida ishtirok etishga jalb qilish, ayrim tergov harakatlarini bajarish yuzasidan koʻrsatmalar beradi; surishtiruv va dastlabki tergov organlarining vakolatiga tegishli boʻlgan jinoyat ishini bitta organdan boshqasiga beradi hamda jinoyat ishini bitta surishtiruvchidan yoki tergovchidan boshqasiga topshiradi; jinoyat ishi boʻyicha dastlabki tergovni shaxsan oʻzi olib boradi; qonunda nazarda tutilgan hollarda va tartibda surishtiruvchi yoki tergovchini ishni olib borishdan chetlatish toʻgʻrisida iltimosnoma kiritadi; tergovga qadar tekshiruv, surishtiruv, dastlabki tergov yuritishda qonun buzilishlariga yoʻl qoʻygan mansabdor shaxslarni javobgarlikka tortish toʻgʻrisida taqdimnoma kiritadi; surishtiruv va dastlabki tergov organlarining qonunlarga rioya etishlari yuzasidan koʻrsatmalar beradi. Prokurorning qonunga asoslangan talablari hamda koʻrsatmalari surishtiruvchi, tergovchi, shuningdek tergovga qadar tekshiruvni amalga oshiruvchi organ mansabdor shaxsi tomonidan bajarilishi majburiydir. Mazkur moddaning birinchi qismida nazarda tutilgan vakolatlardan tashqari prokuror jinoyat ishlarini yuritishning istalgan bosqichida ishtirok etish va zarur hollarda har qanday protsessual harakatni shaxsan oʻzi bajarish huquqiga egadir.$article382$
WHERE code_id = 'criminal_procedure_code' AND article_number = '382';
