-- ═══════════════════════════════════════════════════════════════════════════
-- IRAC kazuslar — IQTISODIY + KONSTITUTSIYAVIY yo'nalishlar (to'liq qamrov)
-- 20260902 migration 5 ta yo'nalishni qamrab olgan; ushbu qo'shimcha
-- iqtisodiy va konstitutsiyaviy yo'nalishlarni ham to'ldiradi (har biri ≥10).
--
-- Idempotent: kategoriyalarda kazus allaqachon mavjud bo'lsa, qayta kiritilmaydi.
-- ═══════════════════════════════════════════════════════════════════════════

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM public.irac_cases
    WHERE category IN ('iqtisodiy', 'konstitutsiyaviy')
  ) THEN
    INSERT INTO public.irac_cases (title, description, category, difficulty, law_references)
    VALUES
  ($$S$$Yetkazib berish shartnomasi bo'yicha to'lovni undirish va penya$$S$$, $$S$$MCHJ 'A' MCHJ 'B'ga 500 mln so'mlik qurilish mahsulotlarini yetkazib bergan. MCHJ 'B' tovarlarni qabul qilib olgan, dalolatnoma imzolangan, ammo 90 kun davomida to'lov qilinmagan. Shartnomada har bir kun uchun 0.1% penya (lekin 10% dan oshmagan miqdorda) belgilangan. MCHJ 'A' sud orqali 500 mln asosiy qarz va 50 mln penya undirishni so'ramoqda.$$S$$, 'iqtisodiy', 'medium', ARRAY[$$S$$O'zbekiston Respublikasi Fuqarolik Kodeksi 437, 442, 444-moddalari$$S$$, $$S$$'Xo'jalik yurituvchi sub'ektlar faoliyatining shartnomaviy-huquqiy bazasi to'g'risida'gi Qonun 25-32-moddalari$$S$$]),
  ($$S$$Qurilish pudrati shartnomasini bekor qilish va kafolat summasi$$S$$, $$S$$Buyurtmachi va Bosh pudratchi o'rtasida 2 mlrd so'mlik bino qurilishi shartnomasi tuzilgan. Pudratchi ishlarni 5 oyga kechiktirgan va oraliq sifat talablariga javob bermagan. Buyurtmachi shartnomani bekor qilish, to'langan 600 mln so'm avansni qaytarish va 200 mln so'm jarima undirish bo'yicha da'vo kiritgan. Pudratchi esa ob'ektda qilingan ishlarni qabul qilishni talab qilmoqda.$$S$$, 'iqtisodiy', 'hard', ARRAY[$$S$$O'zbekiston Respublikasi Fuqarolik Kodeksi 631, 638, 646, 655-moddalari$$S$$, $$S$$Iqtisodiy Protsessual Kodeksi$$S$$]),
  ($$S$$MCHJ ishtirokchilari o'rtasidagi korporativ nizo (Ulushni sotishda imtiyozli huquq)$$S$$, $$S$$MCHJning 40% ulushiga ega bo'lgan ta'sischi o'z ulushini boshqa ishtirokchilarga taklif qilmasdan to'g'ridan-to'g'ri uchinchi shaxsga sotib yuborgan. Qolgan ishtirokchilar imtiyozli sotib olish huquqi buzilganligini da'vo qilib, xaridor huquq va majburiyatlarini o'zlariga o'tkazishni talab qilmoqdalar.$$S$$, 'iqtisodiy', 'hard', ARRAY[$$S$$O'zbekiston Respublikasi 'Mas'uliyati cheklangan hamda qo'shimcha mas'uliyatli jamiyatlar to'g'risida'gi Qonuni 20-moddasi$$S$$]),
  ($$S$$Bankrotlik (To'lovga qobiliyatsizlik) jarayonini boshlash$$S$$, $$S$$Kreditor korxona qarzdor MCHJdan 300 mln so'm qarzni 6 oy davomida undira olmadi. Majburiy ijro byurosi qarzdor nomida mol-mulk yo'qligi sababli ijro hujjatini qaytargan. Kreditor iqtisodiy sudga qarzdorni to'lovga qobiliyatsiz deb topish to'g'risida ariza bilan murojaat qildi.$$S$$, 'iqtisodiy', 'hard', ARRAY[$$S$$O'zbekiston Respublikasi 'To'lovga qobiliyatsizlik to'g'risida'gi Qonuni 4, 5, 36, 40-moddalari$$S$$]),
  ($$S$$Lizing shartnomasi bo'yicha lizing ob'ektini qaytarib olish$$S$$, $$S$$Lizing oluvchi korxona og'ir yuk mashinasining oylik lizing to'lovlarini 4 oy davomida to'lamagan. Lizing beruvchi shartnomani muddatidan oldin bekor qilish, texnikani majburiy qaytarib olish va qolgan qarzni undirishni talab qilmoqda.$$S$$, 'iqtisodiy', 'medium', ARRAY[$$S$$O'zbekiston Respublikasi Fuqarolik Kodeksi 588, 595, 599-moddalari$$S$$, $$S$$O'zbekiston Respublikasi 'Lizing to'g'risida'gi Qonuni$$S$$]),
  ($$S$$Franchayzing shartnomasi bo'yicha royalti to'lovlari va sir saqlash$$S$$, $$S$$Franchayzi xalqaro brend ostida restoran faoliyatini yuritib, 6 oylik royalti to'lovlarini to'lamagan va brendning maxfiy retseptura texnologiyalarini o'zining boshqa shaxsiy restoranlar tarmog'ida qo'llagan. Franchayzer 100 000 AQSH dollari miqdorida jarima va zararni talab qilmoqda.$$S$$, 'iqtisodiy', 'medium', ARRAY[$$S$$O'zbekiston Respublikasi Fuqarolik Kodeksi 862, 868, 873-moddalari$$S$$]),
  ($$S$$Tovar belgisiga bo'lgan mutlaq huquqni himoya qilish$$S$$, $$S$$Mashhur ichimlik ishlab chiqaruvchi MCHJ 'X' boshqa MCHJ 'Y' tomonidan xuddi shunday dizayn va adashtirib yuborish darajasida o'xshash nomdagi ichimlik ishlab chiqarilayotganini aniqladi. Da'vogar mahsulotlarni muomaladan chiqarish, yo'q qilish va 300 mln so'm zarar undirishni so'ramoqda.$$S$$, 'iqtisodiy', 'medium', ARRAY[$$S$$O'zbekiston Respublikasi 'Tovar belgilari, xizmat ko'rsatish belgilari va tovar kelib chiqqan joy nomlari to'g'risida'gi Qonuni 27-moddasi$$S$$]),
  ($$S$$Sug'urta tovoni to'lashni rad etish bo'yicha nizo$$S$$, $$S$$Omborxonada sodir bo'lgan yong'in oqibatida 1 mlrd so'mlik tovar nobud bo'lgan. Sug'urta kompaniyasi yong'in xavfsizligi qoidalariga rioya etilmaganligini sabab qilib sug'urta tovonini to'lashdan bosh tortgan. Sug'urtalovchi esa yong'in qasddan sodir etilmaganini ta'kidlamoqda.$$S$$, 'iqtisodiy', 'medium', ARRAY[$$S$$O'zbekiston Respublikasi Fuqarolik Kodeksi 940, 951, 958-moddalari$$S$$, $$S$$'Sug'urta faoliyati to'g'risida'gi Qonun$$S$$]),
  ($$S$$Davlat xaridlari shartnomasini bajarishdan bir tomonlama bosh tortish$$S$$, $$S$$G'olib deb topilgan yetkazib beruvchi xalqaro bozorda narxlar keskin ko'tarilib ketganini vaj qilib, davlat buyurtmachisiga tovar yetkazib berishdan bosh tortgan. Buyurtmachi korxonani insofsiz ijrochilarning yagona reyestriga kiritish va kafolat ta'minotini davlat daromadiga undirishni talab qilmoqda.$$S$$, 'iqtisodiy', 'hard', ARRAY[$$S$$O'zbekiston Respublikasi 'Davlat xaridlari to'g'risida'gi Qonuni 42, 49-moddalari$$S$$]),
  ($$S$$Faktoring shartnomasi bo'yicha pul talabnomasidan boshqa shaxs foydasiga voz kechish$$S$$, $$S$$Mijoz o'z xaridori bo'lgan uchinchi shaxsga nisbatan bo'lgan 400 mln so'mlik qarz talabnomasini bankka (faktorga) bergan. Xaridor tovar nuqsonli bo'lgani sababli bankka to'lov qilishdan bosh tortmoqda va bankdan o'zaro hisob-kitobni mijoz bilan hal qilishni talab qilmoqda.$$S$$, 'iqtisodiy', 'hard', ARRAY[$$S$$O'zbekiston Respublikasi Fuqarolik Kodeksi 749, 755, 757-moddalari$$S$$]),
  ($$S$$Yangi Konstitutsiya bo'yicha inson qadr-qimmati va shaxsiy daxlsizlik$$S$$, $$S$$Tergov organi tomonidan gumon qilinuvchining uyi sud qarorisiz, faqat tergovchi qarori bilan 'kechiktirib bo'lmaydigan holat' degan vaj bilan tintuv qilingan. Fuqaro Konstitutsiyaviy normalarga tayanib, uy-joy daxlsizligi faqat sud qarori bilan cheklanishi mumkinligini aytib shikoyat qilgan.$$S$$, 'konstitutsiyaviy', 'medium', ARRAY[$$S$$O'zbekiston Respublikasi Konstitutsiyasi 27, 31-moddalari$$S$$, $$S$$JPK 158-moddasi$$S$$]),
  ($$S$$Xabeas Korpus: Qamoqqa olish ehtiyot chorasining konstitutsiyaviy kafolatlari$$S$$, $$S$$Shaxs ushlangandan so'ng 48 soat ichida sudga olib chiqilmasdan 72 soat vaqtincha saqlash hibsxonasida ushlab turilgan. Himoyachi Konstitutsiyaning 27-moddasi buzilganini, shaxs zudlik bilan ozod etilishi shartligini talab qilmoqda.$$S$$, 'konstitutsiyaviy', 'hard', ARRAY[$$S$$O'zbekiston Respublikasi Konstitutsiyasi 27-moddasi (Qamoqqa olishga faqat sud qarori asosida yo'l qo'yilishi)$$S$$]),
  ($$S$$Aybsizlik prezumpsiyasi va o'ziga qarshi ko'rsatma bermaslik huquqi (Miranda qoidasi)$$S$$, $$S$$Gumonlanuvchiga ushlangan paytida sukut saqlash va advokatga ega bo'lish huquqlari tushuntirilmagan. Shaxs bosim ostida o'z aybiga iqrorlik arizasi yozib bergan. Himoyachi sudda ushbu ko'rsatmalarni Konstitutsiyaga zid deb topib, dalillar qatoridan chiqarishni so'ramoqda.$$S$$, 'konstitutsiyaviy', 'medium', ARRAY[$$S$$O'zbekiston Respublikasi Konstitutsiyasi 28-moddasi$$S$$, $$S$$JPK 17, 22-moddalari$$S$$]),
  ($$S$$Mulk daxlsizligi va mulkni musodara qilishning konstitutsiyaviy asoslari$$S$$, $$S$$Ma'muriy komissiya qarori bilan fuqaroning noqonuniy savdo qilgan tovarlari to'g'ridan-to'g'ri davlat daromadiga musodara qilingan. Fuqaro mulkdan mahrum qilish faqat qonuniy sud qarori bilan amalga oshirilishi kerakligini ta'kidlamoqda.$$S$$, 'konstitutsiyaviy', 'hard', ARRAY[$$S$$O'zbekiston Respublikasi Konstitutsiyasi 65, 66-moddalari (Xususiy mulk daxlsizligi)$$S$$]),
  ($$S$$Advokat yordami olish huquqining konstitutsiyaviy kafolatlari$$S$$, $$S$$Og'ir jinoyatda ayblanayotgan shaxsga tergov davomida advokat tanlash imkoni berilmagan, davlat hisobidan tayinlangan advokat esa tergov harakatlarida amalda qatnashmagan. Sud jarayonida ayblanuvchi himoya huquqi buzilganini bildirgan.$$S$$, 'konstitutsiyaviy', 'medium', ARRAY[$$S$$O'zbekiston Respublikasi Konstitutsiyasi 29-moddasi (Malakali yuridik yordam olish huquqi)$$S$$]),
  ($$S$$Tenglik prinsipi va kamsitishga (diskriminatsiyaga) yo'l qo'yilmasligi$$S$$, $$S$$Davlat xizmatiga qabul qilish bo'yicha tanlov e'lonida nomzodlarning jinsi (faqat erkaklar) va yoshi (30 yoshgacha) bo'yicha cheklovlar qo'yilgan. 32 yoshli ayol nomzod ushbu tanlov qoidalarini Konstitutsiyaga zid deb topishni so'ramoqda.$$S$$, 'konstitutsiyaviy', 'easy', ARRAY[$$S$$O'zbekiston Respublikasi Konstitutsiyasi 19, 37-moddalari$$S$$, $$S$$'Davlat fuqarolik xizmati to'g'risida'gi Qonun$$S$$]),
  ($$S$$Tibbiy yordam olish va sog'liqni saqlash huquqi$$S$$, $$S$$Davlat shifoxonasi shoshilinch tez tibbiy yordamga muhtoj bo'lgan fuqarodan dastlab to'lov qilishni yoki sug'urta polisini talab qilib, tibbiy yordam ko'rsatishni kechiktirgan. Oqibatda bemorning ahvoli og'irlashgan.$$S$$, 'konstitutsiyaviy', 'easy', ARRAY[$$S$$O'zbekiston Respublikasi Konstitutsiyasi 48-moddasi (Bepul kafolatlangan tibbiy yordam)$$S$$]),
  ($$S$$Ta'lim olish huquqi va oliy ta'lim muassasalarining akademik erkinligi$$S$$, $$S$$Universitet talabasi shaxsiy ijtimoiy tarmoq sahifasida ta'lim sifatini tanqid qilgan posti uchun rektor buyrug'i bilan o'qishdan chetlashtirilgan. Talaba fikr bildirish erkinligi va ta'lim olish huquqi buzilgani bo'yicha sudga murojaat qilgan.$$S$$, 'konstitutsiyaviy', 'medium', ARRAY[$$S$$O'zbekiston Respublikasi Konstitutsiyasi 33, 50, 51-moddalari$$S$$]),
  ($$S$$Konstitutsiyaviy sudga fuqarolarning to'g'ridan-to'g'ri murojaat qilish huquqi$$S$$, $$S$$Fuqaro barcha sud instansiyalarini o'tib, uning ishida qo'llanilgan qonun normasi Konstitutsiyaning inson huquqlariga oid qoidalariga zid kelishini aniqlagan. Fuqaro Konstitutsiyaviy sudga ushbu qonun normasining konstitutsiyaviyligini tekshirish to'g'risida to'g'ridan-to'g'ri shikoyat kiritdi.$$S$$, 'konstitutsiyaviy', 'hard', ARRAY[$$S$$O'zbekiston Respublikasi Konstitutsiyasi 133-moddasi$$S$$, $$S$$'Konstitutsiyaviy sud to'g'risida'gi Konstitutsiyaviy Qonun 27-moddasi$$S$$]),
  ($$S$$Atrof-muhitga oid huquqlar: Qulay tabiiy muhitga ega bo'lish huquqi$$S$$, $$S$$Aholi turar joy massivida yashovchi fuqarolar yaqin atrofda noqonuniy ravishda qurilayotgan, havoni ifloslantiruvchi zavod qurilishini to'xtatish va yashil hududni saqlab qolish talabi bilan jamoaviy konstitutsiyaviy da'vo qo'zg'atdilar.$$S$$, 'konstitutsiyaviy', 'medium', ARRAY[$$S$$O'zbekiston Respublikasi Konstitutsiyasi 49-moddasi (Qulay atrof-muhitga, uning holati to'g'risida ishonchli axborotga ega bo'lish huquqi)$$S$$]),
  ($$S$$Xalqaro tijorat arbitraji qarorlarini tan olish va ijroga qaratish$$S$$, $$S$$London xalqaro arbitraj sudi (LCIA) O'zbekiston kompaniyasidan xorijiy kompaniya foydasiga 2 mln dollar undirish haqida qaror qabul qilgan. Xorijiy kompaniya Toshkent shahar sudiga ushbu qarorni ijroga qaratish to'g'risida ariza kiritgan. O'zbekiston kompaniyasi esa jamoat tartibiga zidligini vaj qilmoqda.$$S$$, 'iqtisodiy', 'hard', ARRAY[$$S$$1958-yilgi Nyu-York Konvensiyasi$$S$$, $$S$$O'zbekiston Respublikasi 'Xalqaro tijorat arbitraji to'g'risida'gi Qonuni 51, 52-moddalari$$S$$]);
  END IF;
END $$;
